spring:
  datasource:
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:}
      expiration: ${JWT_EXPIRATION:}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:}




